# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Random 1
        run: |
          exit 1 #$((( RANDOM % 2 )))
        shell: bash
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Random 2
        run: |
          exit $((( RANDOM % 2 )))
        shell: bash
#   job2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Succeed
#         run: |
#           echo "ok"

  run-if-failed:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always() && failure()
    steps:
      - name: Needs context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"
  
  run-if-succeded:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always() && success()
    steps:
      - name: Needs context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"
